### ISSUE TITLE
Code generator  not working on flutter 3.16.5

### ISSUE THREAD

**Issue by thealmamun** [TekExplorer/riverpod_mutations_generator#1]
riverpod code generation is not working for this class

@riverpod
class AssistantProvider extends **_AssistantProvider** {

}

when i run command `dart run build_runner watch` it's showing error with flutter version 3.16.5 where downgrading version 3.3.0 is working fine. 

`[SEVERE] riverpod_generator on lib/provider/assistant/assistant_provider.dart:

No "build" method found. Classes annotated with @riverpod must define a method named "build".
[INFO] Running build completed, took 11.5s
[INFO] Caching finalized dependency graph completed, took 74ms
[SEVERE] Failed after 11.6s
[SEVERE] Terminating builds due to package graph update, please restart the build.
[INFO] Terminating. No further builds will be scheduled
[INFO] Builds finished. Safe to exit
`

`My flutter doctor -v
[!] Flutter (Channel stable, 3.16.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-DE)
    • Flutter version 3.16.5 on channel stable at /Users/almamun/Documents/developer/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/almamun/Documents/developer/flutter. Consider adding /Users/almamun/Documents/developer/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (8 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/almamun/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/almamun/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
`

**Comment by TekExplorer** [comment]
Seems self explanatory. I don't see a build method.
Additionally, this is a riverpod issue, not my generator.
